// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARt5sErYqK0GNAMI36n0NtDkK6IP8AfeQ',
    appId: '1:636367443896:web:cb2c9e933a702c4508614d',
    messagingSenderId: '636367443896',
    projectId: 'live-scores-b5262',
    authDomain: 'live-scores-b5262.firebaseapp.com',
    storageBucket: 'live-scores-b5262.firebasestorage.app',
    measurementId: 'G-QVND310XF9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOcsJ6ZoWz3-k-Df28OSVYmv9tfNtNwhQ',
    appId: '1:636367443896:android:d1466d8e40a0f3e208614d',
    messagingSenderId: '636367443896',
    projectId: 'live-scores-b5262',
    storageBucket: 'live-scores-b5262.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlbuj_BnVS5yz17Won31ZjAwCtCqCOsjg',
    appId: '1:636367443896:ios:528058f6a2d5bd7e08614d',
    messagingSenderId: '636367443896',
    projectId: 'live-scores-b5262',
    storageBucket: 'live-scores-b5262.firebasestorage.app',
    iosBundleId: 'com.example.liveScores',
  );
}
